// <auto-generated />
using System;
using DocumentAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parse.Migrations
{
    [DbContext(typeof(DocumentContext))]
    [Migration("20220916152031_InfoType")]
    partial class InfoType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("KONSTANT")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TOTALANTAL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TOTALBELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsStartId");

                    b.ToTable("OsInfoEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFDELINGSNUMMER")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("AFTALENUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ANTAL_INFO_RECORDS")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CPR_NUMMER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORTEGN")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("INDBETALT_BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("KUNDENUMMER_AFSENDER")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("KUNDENUMMER_MODTAGER")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OVERENSKOMSTNUMMER")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsSectionStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PBSNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PERIODE_FRA")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PERIODE_TIL")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SPECIFICERET_BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsSectionStartId");

                    b.ToTable("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord01", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFLONNINGSFORM")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ANCIENNITET_FRA_DATO")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FRATRAEDELSESDATO")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("KUNDENAVN")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("OPLYSNINGSKODE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PENSIONSALDER")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PENSIONSALDERKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVETEKST")
                        .HasMaxLength(37)
                        .HasColumnType("nvarchar(37)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("STARTDATO_AFLONNINGSFORM")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_KUNDE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord01");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord02", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ARBEJDSGIVERS_ANDEL_AF_NORMALBIDRAG")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ARBEJDSGIVER_PENSIONSBIDRAGSPROCENT")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GRUPPELIVSANDEL_AF_INDBETALT_BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("LONTRIN")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NORMALBIDRAG")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PENSIONSBIDRAGSPROCENT")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PENSIONSGIVENDE_LON")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PENSIONSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("STARTDATO_GRUPPELIVSANDEL")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_LONTRIN")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_NORMALBIDRAG")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_PENSIONSBIDRAGSPROCENT")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_PENSIONSGIVENDE_LON")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_PENSIONSTYPE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord02");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord03", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFVIGELSESBELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("AFVIGELSESKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("AFVIGELSESPROCENT")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BESKAEFTIGELSESGRAD")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BESKAEFTIGELSESGRAD_NAEVNER")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("BESKAEFTIGELSESGRAD_TAELLER")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORTEGN")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVETEKST")
                        .HasMaxLength(58)
                        .HasColumnType("nvarchar(58)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("STARTDATO_AFVIGELSE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_BESKAEFTIGELSESGRAD")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord03");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord04", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FILLER")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("FORTEGN1")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FORTEGN2")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FORTEGN3")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("REGULERINGSBELOB1")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("REGULERINGSBELOB2")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("REGULERINGSBELOB3")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("REGULERINGSKODE1")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("REGULERINGSKODE2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("REGULERINGSKODE3")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SLUTDATO_REGULERING1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SLUTDATO_REGULERING2")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SLUTDATO_REGULERING3")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_REGULERING1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_REGULERING2")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_REGULERING3")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord04");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord05", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADRESSE1")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ADRESSE2")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BYNAVN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("POSTNUMMER")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVETEKST")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TAL1")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TAL2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord05");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord10", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVE1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RESERVE1KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RESERVE2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RESERVE2KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RESERVE3")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RESERVE3KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RESERVE4")
                        .HasMaxLength(61)
                        .HasColumnType("nvarchar(61)");

                    b.Property<string>("RESERVE4KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord10");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFSENDERKONTONUMMER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AFSENDERREGISTRERINGSNUMMER")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ANTAL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CVRNUMMERAFSENDER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DISPOSITIONSDATO")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsSectionStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PBSNUMMERMODTAGER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsSectionStartId");

                    b.ToTable("OsSectionEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CVRNUMMERAFSENDER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DISPOSITIONSDATO")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("KONTONUMMER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OVERFORSELSART")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PBSNUMMERMODTAGER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("REGISTRERINGSNUMMER")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsStartId");

                    b.ToTable("OsSectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("IDENTIFIKATION")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KONSTANT")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LEVERANCEKVITTERING")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SYSTEMTEKST")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OsInfoStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoEnd", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", "OsStart")
                        .WithMany("OsInfoEndCollection")
                        .HasForeignKey("OsStartId");

                    b.Navigation("OsStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", "OsSectionStart")
                        .WithMany("OsRecord00Collection")
                        .HasForeignKey("OsSectionStartId");

                    b.Navigation("OsSectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord01", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord01Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord02", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord02Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord03", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord03Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord04", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord04Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord05", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord05Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord10", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord10Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionEnd", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", "OsSectionStart")
                        .WithMany("OsSectionEnd")
                        .HasForeignKey("OsSectionStartId");

                    b.Navigation("OsSectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", "OsStart")
                        .WithMany("OsInfoSectionStartCollection")
                        .HasForeignKey("OsStartId");

                    b.Navigation("OsStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", b =>
                {
                    b.Navigation("OsRecord01Collection");

                    b.Navigation("OsRecord02Collection");

                    b.Navigation("OsRecord03Collection");

                    b.Navigation("OsRecord04Collection");

                    b.Navigation("OsRecord05Collection");

                    b.Navigation("OsRecord10Collection");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", b =>
                {
                    b.Navigation("OsRecord00Collection");

                    b.Navigation("OsSectionEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", b =>
                {
                    b.Navigation("OsInfoEndCollection");

                    b.Navigation("OsInfoSectionStartCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
