// <auto-generated />
using System;
using DocumentAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parse.Migrations
{
    [DbContext(typeof(DocumentContext))]
    partial class DocumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord22", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BsRecord42Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DataRecordNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<string>("Name")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BsRecord42Id");

                    b.ToTable("BsRecord22");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord2209", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BsRecord42Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DataRecordNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Filler03")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BsRecord42Id")
                        .IsUnique()
                        .HasFilter("[BsRecord42Id] IS NOT NULL");

                    b.ToTable("BsRecord2209");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord2210", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BsRecord42Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DataRecordNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorCvrCpr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DispatchSpeed")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("MandatoryPrint")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BsRecord42Id")
                        .IsUnique()
                        .HasFilter("[BsRecord42Id] IS NOT NULL");

                    b.ToTable("BsRecord2210");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord42", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DataRecordNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MandateNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("PayerId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PaymentDate")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Reference")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("SectionStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("SectionStartId");

                    b.ToTable("BsRecord42");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord52", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BsRecord42Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DataRecordNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("MandateNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TextLine")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BsRecord42Id");

                    b.ToTable("BsRecord52");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord62", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BsRecord42Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DataRecordNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Filler03")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TextLine")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("BsRecord42Id");

                    b.ToTable("BsRecord62");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Delivery601End", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DataSupplierCvr")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid?>("DeliveryStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("NumberOfRecord22")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NumberOfRecord42")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NumberOfRecord5262")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NumberOfSections")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("SubSystem")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TotalAmount")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStartId");

                    b.ToTable("Bs601End");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Delivery601Start", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DataSupplierCvr")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DeliveryCreationDate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DeliveryId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<string>("SubSystem")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Bs601Start");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Section0112End", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler01")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Filler03")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Filler04")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("NumberOfRecord22")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NumberOfRecord42")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NumberOfRecord5262")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SectionNumber")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<Guid?>("SectionStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.Property<string>("TotalAmount")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("SectionStartId");

                    b.ToTable("Bs601SectionEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Section0112Start", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataRecordType")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DataSupplierId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DebtorGroupNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DeliveryCreationDate")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid?>("DeliveryStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Filler01")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Filler02")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Filler03")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Filler04")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MainTextLine")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PbsNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SectionNumber")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("SystemId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStartId");

                    b.ToTable("Bs601SectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("KONSTANT")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TOTALANTAL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TOTALBELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsStartId");

                    b.ToTable("OsInfoEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFDELINGSNUMMER")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("AFTALENUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ANTAL_INFO_RECORDS")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CPR_NUMMER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORTEGN")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("INDBETALT_BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("KUNDENUMMER_AFSENDER")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("KUNDENUMMER_MODTAGER")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OVERENSKOMSTNUMMER")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsSectionStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PBSNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PERIODE_FRA")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PERIODE_TIL")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SPECIFICERET_BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsSectionStartId");

                    b.ToTable("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord01", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFLONNINGSFORM")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ANCIENNITET_FRA_DATO")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FRATRAEDELSESDATO")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("KUNDENAVN")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("OPLYSNINGSKODE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PENSIONSALDER")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PENSIONSALDERKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVETEKST")
                        .HasMaxLength(37)
                        .HasColumnType("nvarchar(37)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("STARTDATO_AFLONNINGSFORM")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_KUNDE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord01");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord02", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ARBEJDSGIVERS_ANDEL_AF_NORMALBIDRAG")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ARBEJDSGIVER_PENSIONSBIDRAGSPROCENT")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GRUPPELIVSANDEL_AF_INDBETALT_BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("LONTRIN")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NORMALBIDRAG")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PENSIONSBIDRAGSPROCENT")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PENSIONSGIVENDE_LON")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PENSIONSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("STARTDATO_GRUPPELIVSANDEL")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_LONTRIN")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_NORMALBIDRAG")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_PENSIONSBIDRAGSPROCENT")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_PENSIONSGIVENDE_LON")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_PENSIONSTYPE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord02");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord03", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFVIGELSESBELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("AFVIGELSESKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("AFVIGELSESPROCENT")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BESKAEFTIGELSESGRAD")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BESKAEFTIGELSESGRAD_NAEVNER")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("BESKAEFTIGELSESGRAD_TAELLER")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FORTEGN")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVETEKST")
                        .HasMaxLength(58)
                        .HasColumnType("nvarchar(58)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("STARTDATO_AFVIGELSE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_BESKAEFTIGELSESGRAD")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord03");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord04", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FILLER")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("FORTEGN1")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FORTEGN2")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FORTEGN3")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("REGULERINGSBELOB1")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("REGULERINGSBELOB2")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("REGULERINGSBELOB3")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("REGULERINGSKODE1")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("REGULERINGSKODE2")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("REGULERINGSKODE3")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SLUTDATO_REGULERING1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SLUTDATO_REGULERING2")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SLUTDATO_REGULERING3")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_REGULERING1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_REGULERING2")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("STARTDATO_REGULERING3")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord04");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord05", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADRESSE1")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ADRESSE2")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BYNAVN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("POSTNUMMER")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVETEKST")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TAL1")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TAL2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord05");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord10", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("INFORECORDTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsRecord00Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RESERVE1")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RESERVE1KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RESERVE2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RESERVE2KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RESERVE3")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RESERVE3KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RESERVE4")
                        .HasMaxLength(61)
                        .HasColumnType("nvarchar(61)");

                    b.Property<string>("RESERVE4KODE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SEKVENSNUMMER")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsRecord00Id");

                    b.ToTable("OsRecord10");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionEnd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFSENDERKONTONUMMER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AFSENDERREGISTRERINGSNUMMER")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ANTAL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BELOB")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CVRNUMMERAFSENDER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DISPOSITIONSDATO")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("OVERFORSELSTYPE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsSectionStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PBSNUMMERMODTAGER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsSectionStartId");

                    b.ToTable("OsSectionEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CVRNUMMERAFSENDER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DISPOSITIONSDATO")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("INFOTYPE")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("KONTONUMMER")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OVERFORSELSART")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid?>("OsStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PBSNUMMERMODTAGER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("REGISTRERINGSNUMMER")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsStartId");

                    b.ToTable("OsSectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATALEVERANDORNUMMER")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("IDENTIFIKATION")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KONSTANT")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LEVERANCEKVITTERING")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RECORDTYPE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("SYSTEMKODE")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SYSTEMTEKST")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<long>("TenantÍd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OsInfoStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord22", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.BsRecord42", "BsRecord42")
                        .WithMany("Bs22Records")
                        .HasForeignKey("BsRecord42Id");

                    b.Navigation("BsRecord42");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord2209", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.BsRecord42", "BsRecord42")
                        .WithOne("BsRecord2209")
                        .HasForeignKey("ExternalModels.MasterCard.Bs601Model.BsRecord2209", "BsRecord42Id");

                    b.Navigation("BsRecord42");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord2210", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.BsRecord42", "BsRecord42")
                        .WithOne("BsRecord2210")
                        .HasForeignKey("ExternalModels.MasterCard.Bs601Model.BsRecord2210", "BsRecord42Id");

                    b.Navigation("BsRecord42");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord42", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.Section0112Start", "SectionStart")
                        .WithMany("Bs42Records")
                        .HasForeignKey("SectionStartId");

                    b.Navigation("SectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord52", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.BsRecord42", "BsRecord42")
                        .WithMany("Bs52Records")
                        .HasForeignKey("BsRecord42Id");

                    b.Navigation("BsRecord42");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord62", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.BsRecord42", "BsRecord42")
                        .WithMany("Bs62Records")
                        .HasForeignKey("BsRecord42Id");

                    b.Navigation("BsRecord42");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Delivery601End", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.Delivery601Start", "DeliveryStart")
                        .WithMany("DeliveryEnd")
                        .HasForeignKey("DeliveryStartId");

                    b.Navigation("DeliveryStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Section0112End", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.Section0112Start", "SectionStart")
                        .WithMany("SectionEnd")
                        .HasForeignKey("SectionStartId");

                    b.Navigation("SectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Section0112Start", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.Bs601Model.Delivery601Start", "DeliveryStart")
                        .WithMany("BsSectionStart")
                        .HasForeignKey("DeliveryStartId");

                    b.Navigation("DeliveryStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoEnd", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", "OsStart")
                        .WithMany("OsInfoEndCollection")
                        .HasForeignKey("OsStartId");

                    b.Navigation("OsStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", "OsSectionStart")
                        .WithMany("OsRecord00Collection")
                        .HasForeignKey("OsSectionStartId");

                    b.Navigation("OsSectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord01", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord01Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord02", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord02Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord03", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord03Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord04", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord04Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord05", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord05Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord10", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", "OsRecord00")
                        .WithMany("OsRecord10Collection")
                        .HasForeignKey("OsRecord00Id");

                    b.Navigation("OsRecord00");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionEnd", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", "OsSectionStart")
                        .WithMany("OsSectionEnd")
                        .HasForeignKey("OsSectionStartId");

                    b.Navigation("OsSectionStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", b =>
                {
                    b.HasOne("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", "OsStart")
                        .WithMany("OsInfoSectionStartCollection")
                        .HasForeignKey("OsStartId");

                    b.Navigation("OsStart");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.BsRecord42", b =>
                {
                    b.Navigation("Bs22Records");

                    b.Navigation("Bs52Records");

                    b.Navigation("Bs62Records");

                    b.Navigation("BsRecord2209");

                    b.Navigation("BsRecord2210");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Delivery601Start", b =>
                {
                    b.Navigation("BsSectionStart");

                    b.Navigation("DeliveryEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.Bs601Model.Section0112Start", b =>
                {
                    b.Navigation("Bs42Records");

                    b.Navigation("SectionEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoRecord00", b =>
                {
                    b.Navigation("OsRecord01Collection");

                    b.Navigation("OsRecord02Collection");

                    b.Navigation("OsRecord03Collection");

                    b.Navigation("OsRecord04Collection");

                    b.Navigation("OsRecord05Collection");

                    b.Navigation("OsRecord10Collection");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoSectionStart", b =>
                {
                    b.Navigation("OsRecord00Collection");

                    b.Navigation("OsSectionEnd");
                });

            modelBuilder.Entity("ExternalModels.MasterCard.OsInfoModel.OsInfoStart", b =>
                {
                    b.Navigation("OsInfoEndCollection");

                    b.Navigation("OsInfoSectionStartCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
