# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: orchestrator
services:
- name: orchestrator
  image: ${DOCKER_REGISTRY-}orchestrator
  dockerFile: src/Services/Orchestrator/Dockerfile
  bindings:
  - port: 5001
    containerPort: 80
    protocol: http
  - port: 55001
    containerPort: 50001
    protocol: http
- name: orchestrator-dapr
  image: daprio/daprd:latest
- name: ingestion
  image: ${DOCKER_REGISTRY-}ingestion
  dockerFile: src/Services/Ingestion/Dockerfile
  bindings:
  - port: 5010
    containerPort: 80
    protocol: http
  - port: 55010
    containerPort: 50001
    protocol: http
- name: ingestion-dapr
  image: daprio/daprd:latest
- name: parse
  image: ${DOCKER_REGISTRY-}parse
  dockerFile: src/Services/Parse/Dockerfile
  bindings:
  - port: 5020
    containerPort: 80
    protocol: http
  - port: 55020
    containerPort: 50001
    protocol: http
- name: parse-dapr
  image: daprio/daprd:latest
- name: convert
  image: ${DOCKER_REGISTRY-}convert
  dockerFile: src/Services/Convert/Dockerfile
  bindings:
  - port: 5030
    containerPort: 80
    protocol: http
  - port: 55030
    containerPort: 50001
    protocol: http
- name: convert-dapr
  image: daprio/daprd:latest
- name: validate
  image: ${DOCKER_REGISTRY-}validate
  dockerFile: src/Services/Validate/Dockerfile
  bindings:
  - port: 5040
    containerPort: 80
    protocol: http
  - port: 55040
    containerPort: 50001
    protocol: http
- name: validate-dapr
  image: daprio/daprd:latest
- name: pay
  image: ${DOCKER_REGISTRY-}pay
  dockerFile: src/Services/Pay/Dockerfile
  bindings:
  - port: 5055
    containerPort: 80
    protocol: http
  - port: 55055
    containerPort: 50001
    protocol: http
- name: pay-dapr
  image: daprio/daprd:latest
- name: document
  image: ${DOCKER_REGISTRY-}document
  dockerFile: src/Services/Document/Dockerfile
  bindings:
  - port: 5060
    containerPort: 80
    protocol: http
  - port: 55060
    containerPort: 50001
    protocol: http
- name: document-dapr
  image: daprio/daprd:latest
- name: transfer
  image: ${DOCKER_REGISTRY-}transfer
  dockerFile: src/Services/Transfer/Dockerfile
  bindings:
  - port: 5090
    containerPort: 80
    protocol: http
  - port: 55090
    containerPort: 50001
    protocol: http
- name: transfer-dapr
  image: daprio/daprd:latest
- name: administration
  image: ${DOCKER_REGISTRY-}administration
  dockerFile: src/Web/Administration/Dockerfile
  bindings:
  - port: 5100
    containerPort: 80
    protocol: http
  - port: 55100
    containerPort: 50001
    protocol: http
- name: administration-dapr
  image: daprio/daprd:latest
