// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ScenarioTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StateMachineFeature : object, Xunit.IClassFixture<StateMachineFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "StateMachine.feature"
#line hidden
        
        public StateMachineFeature(StateMachineFeature.FixtureData fixtureData, ScenarioTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "StateMachine", "Testing the State Machine", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="GetNextState")]
        [Xunit.TraitAttribute("FeatureTitle", "StateMachine")]
        [Xunit.TraitAttribute("Description", "GetNextState")]
        [Xunit.TraitAttribute("Category", "tag1")]
        [Xunit.InlineDataAttribute("HandleOsInfo", "Receive", "Parse", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "Parse", "Convert", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "Convert", "Validate", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "Validate", "Pay", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "Pay", "GenerateReceipt", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "GenerateReceipt", "TransferResult", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "TransferResult", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("HandleOsInfo", "WorkFlowCompleted", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("GenerateIs", "Consolidate", "Pay", new string[0])]
        [Xunit.InlineDataAttribute("GenerateIs", "Pay", "TransferResult", new string[0])]
        [Xunit.InlineDataAttribute("GenerateIs", "TransferResult", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("GenerateIs", "WorkFlowCompleted", "WorkFlowCompleted", new string[0])]
        public void GetNextState(string event_Type, string process_State, string next_Process_State, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "tag1"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Event_Type", event_Type);
            argumentsOfScenario.Add("Process_State", process_State);
            argumentsOfScenario.Add("Next_Process_State", next_Process_State);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GetNextState", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.When(string.Format("the event with EventType {0} and ProcessState {1}", event_Type, process_State), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then(string.Format("the ProcessState of the next event is {0}", next_Process_State), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                StateMachineFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                StateMachineFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
